name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-buildpkg@v1
        with:
          version: '1.10'
      - run: julia 'data/manual_data_loader.jl'
